### ISSUE TITLE
That "free" list

### ISSUE THREAD

**Issue by KeinNameVorhanden** [cranndarach/username_generator#1]
The site is down, and also why don't you share the txt.

**Comment by cranndarach** [comment]
I initially didn't include the text files because the page where you can view the list without downloading it requests that it not be copied to another site. But then I saw that the actual download page *does* grant permission to copy it to another site, as long as credit is given. So I've uploaded the text files now.

As for the links, that's odd. I've double checked them and they seem to be working for me.
